<?php

add_action('acf/init', function () {

    acf_add_options_page(array(
    'page_title' => 'Theme General Settings',
    'menu_slug' => 'theme-general-settings',
    'menu_title' => 'Theme Settings',
    'position' => '',
    'redirect' => false,
    'menu_icon' => array(
        'type' => 'dashicons',
        'value' => 'dashicons-admin-generic',
    ),
    'icon_url' => 'dashicons-admin-generic',
    ));
    acf_add_options_page(array(
    'page_title' => 'Theme Footer Settings',
    'menu_slug' => 'theme-footer-settings',
    'parent_slug' => 'theme-general-settings',
    'menu_title' => 'Footer',
    'position' => '',
    'redirect' => false,
    ));
    acf_add_options_page(array(
    'page_title' => 'Theme Front Page Settings',
    'menu_slug' => 'theme-front-page-settings',
    'parent_slug' => 'theme-general-settings',
    'menu_title' => 'Front Page',
    'position' => '',
    'redirect' => false,
    ));
});

add_action('acf/include_fields', function () {
    if (! function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_66b1d13b73ae0',
        'title' => 'Footer (copy)',
        'fields' => array(
            array(
                'key' => 'field_66b1d13b78781',
                'label' => 'Sections',
                'name' => 'footer',
                'aria-label' => '',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_66b0c1a87b53b' => array(
                        'key' => 'layout_66b0c1a87b53b',
                        'name' => 'newsletter_section',
                        'label' => 'Newsletter Section',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_66b1d13b7a577',
                                'label' => 'Main',
                                'name' => '',
                                'aria-label' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                                'selected' => 0,
                            ),
                            array(
                                'key' => 'field_66b1d13b7a58f',
                                'label' => 'Title',
                                'name' => 'title_main',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_66b1d13b7a595',
                                'label' => 'Description',
                                'name' => 'description_main',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'placeholder' => '',
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_66b1d13b7a59e',
                                'label' => 'Button Text',
                                'name' => 'button_text_main',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_66b1d13b7a5a5',
                                'label' => 'Modal',
                                'name' => '',
                                'aria-label' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                                'selected' => 0,
                            ),
                            array(
                                'key' => 'field_66b1d13b7a5ad',
                                'label' => 'Title',
                                'name' => 'title_modal',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_66b1d13b7a5b3',
                                'label' => 'Description',
                                'name' => 'description_modal',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'placeholder' => '',
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_66b1d13b7a5b9',
                                'label' => 'Button Text',
                                'name' => 'button_text_modal',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_66b0c37323a6d' => array(
                        'key' => 'layout_66b0c37323a6d',
                        'name' => 'promotion_section',
                        'label' => 'Promotion Section',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_66b1d13b7a5c1',
                                'label' => 'Description',
                                'name' => 'description_promotion',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'placeholder' => '',
                                'new_lines' => '',
                            ),
                            array(
                                'key' => 'field_66b1d13b7a5c8',
                                'label' => 'Slogans',
                                'name' => 'slogans_promotion',
                                'aria-label' => '',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'table',
                                'min' => 0,
                                'max' => 0,
                                'collapsed' => '',
                                'button_label' => 'Add Row',
                                'rows_per_page' => 20,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_66b1d13b8cfac',
                                        'label' => 'Slogan',
                                        'name' => 'slogan_repeater',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'parent_repeater' => 'field_66b1d13b7a5c8',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_66b0c3fb23a72' => array(
                        'key' => 'layout_66b0c3fb23a72',
                        'name' => 'social_section',
                        'label' => 'Social Section',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_66b1d13b7a5ce',
                                'label' => 'Button Text',
                                'name' => 'button_text_social',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_66b1d13b7a5d7',
                                'label' => 'Image',
                                'name' => 'image_social',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'preview_size' => 'medium',
                            ),
                            array(
                                'key' => 'field_66b1d13b7a5dd',
                                'label' => 'Instagram Handle',
                                'name' => 'instagram_handle_social',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'min' => '',
                'max' => '',
                'button_label' => 'Add Row',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-footer-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
    'key' => 'group_66b1d60b5eabb',
    'title' => 'Theme Front Page Settings',
    'fields' => array(
        array(
            'key' => 'field_66b1d60b3bc67',
            'label' => 'Sections',
            'name' => 'front_page',
            'aria-label' => '',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                'layout_66b1d646b78da' => array(
                    'key' => 'layout_66b1d646b78da',
                    'name' => 'cover_section',
                    'label' => 'Cover Section',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_66b1d6a33bc68',
                            'label' => 'Cover Image',
                            'name' => 'cover_image',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'preview_size' => 'medium',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_66b1d6c33bc69' => array(
                    'key' => 'layout_66b1d6c33bc69',
                    'name' => 'categories_section',
                    'label' => 'Categories Section',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_66b1d6d13bc6b',
                            'label' => 'Background Image',
                            'name' => 'background_image',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'preview_size' => 'medium',
                        ),
                        array(
                            'key' => 'field_66b1d7603bc6c',
                            'label' => 'Mobile Cover Image',
                            'name' => 'mobile_cover_image',
                            'aria-label' => '',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'preview_size' => 'medium',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'min' => '',
            'max' => '',
            'button_label' => 'Add Row',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'theme-front-page-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_66b1d29e4a84f',
        'title' => 'General Settings (copy)',
        'fields' => array(
            array(
                'key' => 'field_66b1d29e4e749',
                'label' => 'Email',
                'name' => 'email-settings',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});
